name: model-metrics
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_AUTH }}
        run: |     
          echo "# Continuous Machine Learning" > report.md
          
          echo "CML works!!!!!!!!" >> report.md
          
                  
          cml send-comment report.md